# Base image for react
FROM node:16-alpine

# Create working directory
WORKDIR /app

# Copy over just the package json; so it's independant images for caching
COPY ./package.json ./
# Install the dependencies
RUN npm install 

# Copy the rest of the files except for build and node modules
COPY ./ ./

CMD ["npm", "run", "start"]